// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Configure the engine with cluster connection details.
///
/// This must be called after `init_engine` and before `start_engine`.
/// Persists the configuration to disk so that subsequent engine starts
/// will automatically restore the configured state.
///
/// # Arguments
/// * `cluster_id` - Unique identifier for the cluster to join
/// * `server_url` - WebSocket URL of the proxy server
/// * `auth_token` - Authentication token for the cluster
void configureCluster({
  required String clusterId,
  required String serverUrl,
  required String authToken,
}) => RustLib.instance.api.crateApiConfigApiConfigureCluster(
  clusterId: clusterId,
  serverUrl: serverUrl,
  authToken: authToken,
);

/// Get the current cluster configuration as a JSON string.
///
/// Returns a JSON object with `cluster_id`, `server_url`, and
/// `is_configured` fields. The `auth_token` is deliberately excluded
/// from the response for security.
String getClusterConfig() =>
    RustLib.instance.api.crateApiConfigApiGetClusterConfig();

/// Check if the engine has been configured with cluster details.
///
/// Returns `true` if `configure_cluster` has been called (or the
/// configuration was restored from a previous session).
bool isConfigured() => RustLib.instance.api.crateApiConfigApiIsConfigured();
