// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Returns a reference to the global `EventBus` singleton.
Future<void> globalEventBus() =>
    RustLib.instance.api.crateApiEventsGlobalEventBus();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EventBus>>
abstract class EventBus implements RustOpaqueInterface {
  static Future<EventBus> default_() =>
      RustLib.instance.api.crateApiEventsEventBusDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<EventBus> newInstance() =>
      RustLib.instance.api.crateApiEventsEventBusNew();

  Future<BigInt> publish({required EngineEvent event});

  Future<ReceiverEngineEvent> subscribe();

  Future<BigInt> subscriberCount();

  static Future<EventBus> withCapacity({required BigInt capacity}) => RustLib
      .instance
      .api
      .crateApiEventsEventBusWithCapacity(capacity: capacity);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Receiver < EngineEvent >>>
abstract class ReceiverEngineEvent implements RustOpaqueInterface {}

@freezed
sealed class EngineEvent with _$EngineEvent {
  const EngineEvent._();

  const factory EngineEvent.stateChanged({
    required String newState,
    String? role,
  }) = EngineEvent_StateChanged;
  const factory EngineEvent.membershipChanged({
    required int memberCount,
    String? masterId,
  }) = EngineEvent_MembershipChanged;
  const factory EngineEvent.heartbeatReceived({
    required String nodeId,
    required int battery,
    required double cpu,
  }) = EngineEvent_HeartbeatReceived;
  const factory EngineEvent.taskUpdate({
    required String taskId,
    required String status,
  }) = EngineEvent_TaskUpdate;
  const factory EngineEvent.pluginResult({
    required String pluginId,
    required String action,
    required bool success,
  }) = EngineEvent_PluginResult;
  const factory EngineEvent.mqttStatus({required bool connected}) =
      EngineEvent_MqttStatus;
  const factory EngineEvent.peerMeshStatus({required int connectedPeers}) =
      EngineEvent_PeerMeshStatus;
  const factory EngineEvent.successionUpdated({required List<String> line}) =
      EngineEvent_SuccessionUpdated;
  const factory EngineEvent.error({
    required String message,
    required String source,
  }) = EngineEvent_Error;
  const factory EngineEvent.log({
    required String level,
    required String message,
  }) = EngineEvent_Log;
}
