// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_engine_mut`, `with_engine_read`, `with_engine_write`, `with_engine`

/// Initialize the node engine with a persistent storage path.
///
/// Creates or loads the node identity from `{storage_path}/node_identity.json`.
/// Returns the node ID as a string. This must be the first FFI function called.
///
/// Calling this function more than once is a no-op -- the engine is initialized
/// only on the first call.
String initEngine({required String storagePath}) =>
    RustLib.instance.api.crateApiNodeApiInitEngine(storagePath: storagePath);

/// Get current node status as a JSON string.
///
/// Returns a JSON object with the following fields:
/// - `state`: current state display name
/// - `node_id`: the node's unique identifier
/// - `cluster_id`: the configured cluster ID (null if not configured)
/// - `is_configured`: whether cluster configuration is present
/// - `is_active`: whether the node is in the Active state
String getNodeStatus() => RustLib.instance.api.crateApiNodeApiGetNodeStatus();

/// Start the engine and initiate connection to the proxy server.
///
/// Transitions to Connecting state, then spawns an async task that:
/// 1. Connects to the proxy server via TCP
/// 2. Registers the node (handshake)
/// 3. Transitions through Registering -> Active
/// 4. Starts MQTT broker if assigned Master role
/// 5. Spawns a background heartbeat loop
///
/// Returns the assigned role as a string ("Master", "Worker", etc.) on
/// success. On connection failure the engine transitions to Reconnecting.
Future<String> startEngine() =>
    RustLib.instance.api.crateApiNodeApiStartEngine();

/// Shut down the engine gracefully.
///
/// Sends a shutdown signal to all internal listeners and transitions the
/// engine to the ShuttingDown state.
Future<void> shutdownEngine() =>
    RustLib.instance.api.crateApiNodeApiShutdownEngine();

/// Get current cluster members as a JSON string.
///
/// Returns a JSON array of objects, each containing:
/// - `node_id`: the member's unique identifier
/// - `role`: the member's current role (Master, Worker, etc.)
/// - `battery_level`: last reported battery percentage
/// - `cpu_load`: last reported CPU load
/// - `memory_available_mb`: last reported available memory
/// - `active_tasks`: last reported task count
/// - `uptime_secs`: last reported uptime
String getClusterMembers() =>
    RustLib.instance.api.crateApiNodeApiGetClusterMembers();

/// Get current cluster topology as a JSON string.
///
/// Returns a JSON object describing the topology type and structure:
/// - `type`: "Standalone", "Flat", or "Hierarchical"
/// - For Flat: includes `master` and `workers` fields
/// - For Hierarchical: includes `super_master` and `regions` fields
String getClusterTopology() =>
    RustLib.instance.api.crateApiNodeApiGetClusterTopology();

/// Get the current routing table as a JSON string.
///
/// Returns a JSON object mapping node IDs to their best route:
/// - `routes`: array of objects, each containing:
///   - `target`: the target node ID
///   - `method`: "LanDirect", "HolePunch", or "TunnelRelay"
///   - `addr`: the address (for LanDirect and HolePunch; null for TunnelRelay)
///
/// Returns an empty routes array if the router is not initialized (engine
/// not configured).
String getRoutingTable() =>
    RustLib.instance.api.crateApiNodeApiGetRoutingTable();
