// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// List all installed plugins as a JSON array of manifests.
///
/// Each entry includes the plugin's id, name, version, description,
/// author, ABI, entry symbol, capabilities, and current state.
String listPlugins() => RustLib.instance.api.crateApiPluginApiListPlugins();

/// Get detailed information about a specific plugin.
///
/// Returns a JSON object with the manifest fields plus the current
/// plugin state. Returns an error if the plugin is not found.
String getPluginInfo({required String pluginId}) =>
    RustLib.instance.api.crateApiPluginApiGetPluginInfo(pluginId: pluginId);

/// Install a plugin from a manifest and `.so` file path.
///
/// The manifest is provided as a JSON string. The `so_path` points to the
/// shared object binary on disk. The plugin is loaded and initialized
/// immediately.
void installPlugin({required String manifestJson, required String soPath}) =>
    RustLib.instance.api.crateApiPluginApiInstallPlugin(
      manifestJson: manifestJson,
      soPath: soPath,
    );

/// Uninstall a plugin by ID.
///
/// Shuts down the plugin, unloads the library, and removes it from the
/// registry. The plugin's state store is preserved for potential reinstall.
void uninstallPlugin({required String pluginId}) =>
    RustLib.instance.api.crateApiPluginApiUninstallPlugin(pluginId: pluginId);

/// Execute a plugin's main function.
///
/// Accepts a JSON input string and returns the plugin's output as a JSON
/// string. The input is UTF-8 encoded and passed to the plugin as raw
/// bytes; the output is read from the plugin's output buffer and returned
/// as a string.
String executePlugin({required String pluginId, required String inputJson}) =>
    RustLib.instance.api.crateApiPluginApiExecutePlugin(
      pluginId: pluginId,
      inputJson: inputJson,
    );
