// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Submit a task for dispatch to a worker node.
///
/// Accepts a JSON-encoded `TaskPayload` and adds it to the dispatcher's
/// pending queue. Returns the task ID as a string on success.
///
/// # JSON format
/// ```json
/// {
///   "task_id": "auto-generated-if-empty",
///   "task_type": { "Ping": null },
///   "data": {},
///   "timeout_secs": 90,
///   "submitted_at": 1700000000000,
///   "priority": "Normal"
/// }
/// ```
String submitTask({required String taskJson}) =>
    RustLib.instance.api.crateApiTaskApiSubmitTask(taskJson: taskJson);

/// Get the current status of a task.
///
/// Returns a JSON string describing the task's status:
/// `"Pending"`, `{"Dispatched": {"to_node": "..."}}`, `"Completed"`, etc.
/// Returns an error if the task ID is not found.
String getTaskStatus({required String taskId}) =>
    RustLib.instance.api.crateApiTaskApiGetTaskStatus(taskId: taskId);

/// Get the result of a completed task.
///
/// Returns a JSON-encoded `TaskResult` on success, or an error if the task
/// has not completed yet or does not exist.
String getTaskResult({required String taskId}) =>
    RustLib.instance.api.crateApiTaskApiGetTaskResult(taskId: taskId);

/// Get dispatcher statistics as a JSON string.
///
/// Returns:
/// ```json
/// {
///   "pending_count": 5,
///   "dispatched_count": 2,
///   "completed_count": 10
/// }
/// ```
String getDispatcherStats() =>
    RustLib.instance.api.crateApiTaskApiGetDispatcherStats();
