//! Call-related node builders for WhatsApp call stanzas.
//!
//! Ports whatsmeow/call.go — provides node builders for call rejection.
//!
//! Wire format for reject:
//! ```xml
//! <call id="MSG_ID" from="OWN_JID" to="CALLER_JID">
//!   <reject call-id="CALL_ID" call-creator="CALLER_JID" count="0"/>
//! </call>
//! ```

use wacore_binary::builder::NodeBuilder;
use wacore_binary::jid::Jid;
use wacore_binary::node::Node;

/// Parameters for building a call reject stanza.
#[derive(Debug, Clone)]
pub struct RejectCallParams {
    /// The message ID for the stanza (generated by the client).
    pub message_id: String,
    /// Our own JID (non-AD form).
    pub own_jid: Jid,
    /// The caller's JID (non-AD form).
    pub caller: Jid,
    /// The call session ID from the offer.
    pub call_id: String,
}

/// Build a `<call>` node that rejects an incoming call.
///
/// Mirrors whatsmeow's `RejectCall`. Sends a `<reject>` child with the
/// call-id and call-creator attributes.
pub fn build_reject_call(params: &RejectCallParams) -> Node {
    NodeBuilder::new("call")
        .attr("id", &params.message_id)
        .attr("from", params.own_jid.to_string())
        .attr("to", params.caller.to_string())
        .children(vec![NodeBuilder::new("reject")
            .attr("call-id", &params.call_id)
            .attr("call-creator", params.caller.to_string())
            .attr("count", "0")
            .build()])
        .build()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_jid(user: &str) -> Jid {
        Jid::try_from(format!("{}@s.whatsapp.net", user)).unwrap()
    }

    #[test]
    fn test_build_reject_call_structure() {
        let params = RejectCallParams {
            message_id: "3EB0ABCD1234".to_string(),
            own_jid: test_jid("111111"),
            caller: test_jid("222222"),
            call_id: "CALL-9876".to_string(),
        };

        let node = build_reject_call(&params);

        assert_eq!(node.tag, "call");
        assert_eq!(
            node.attrs.get("id").map(|v| v.to_string_value()),
            Some("3EB0ABCD1234".to_string())
        );
        assert_eq!(
            node.attrs.get("from").map(|v| v.to_string_value()),
            Some("111111@s.whatsapp.net".to_string())
        );
        assert_eq!(
            node.attrs.get("to").map(|v| v.to_string_value()),
            Some("222222@s.whatsapp.net".to_string())
        );
    }

    #[test]
    fn test_build_reject_call_has_reject_child() {
        let params = RejectCallParams {
            message_id: "3EB0MSG999".to_string(),
            own_jid: test_jid("111111"),
            caller: test_jid("333333"),
            call_id: "CALL-5555".to_string(),
        };

        let node = build_reject_call(&params);

        let children = node.children().expect("should have children");
        assert_eq!(children.len(), 1);

        let reject = &children[0];
        assert_eq!(reject.tag, "reject");
        assert_eq!(
            reject.attrs.get("call-id").map(|v| v.to_string_value()),
            Some("CALL-5555".to_string())
        );
        assert_eq!(
            reject
                .attrs
                .get("call-creator")
                .map(|v| v.to_string_value()),
            Some("333333@s.whatsapp.net".to_string())
        );
        assert_eq!(
            reject.attrs.get("count").map(|v| v.to_string_value()),
            Some("0".to_string())
        );
    }

    #[test]
    fn test_build_reject_call_no_extra_children() {
        let params = RejectCallParams {
            message_id: "3EB0ID".to_string(),
            own_jid: test_jid("aaa"),
            caller: test_jid("bbb"),
            call_id: "C1".to_string(),
        };

        let node = build_reject_call(&params);
        let children = node.children().unwrap();
        assert_eq!(
            children.len(),
            1,
            "reject call should have exactly one child"
        );

        // The reject child should have no children of its own
        assert!(
            children[0].children().is_none() || children[0].children().unwrap().is_empty(),
            "reject node should have no children"
        );
    }
}
